-- Streamlit-in-Snowflake app for ONE environment (${STREAMLIT_ENV} = DEV | QA | PROD).
-- Deployed per branch by streamlit-deploy.yml. Run by hand from de-pipeline/snowflake/, e.g.:
--   STREAMLIT_ENV=DEV python run_sql.py put:streamlit/app.py=@STREAMLIT_DB.STREAMLIT_DEV.CRYPTO_APP_STAGE streamlit-setup.sql
-- Not applied by infra-deploy.yml; skipped by infra-ci (.sqlfluffignore).

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS STREAMLIT_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STREAMLIT_DB;
CREATE SCHEMA IF NOT EXISTS STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV};
CREATE STAGE IF NOT EXISTS STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV}.CRYPTO_APP_STAGE;

-- reads PROD_DB by default (switchable in-app); only the app object is per-env
CREATE OR REPLACE STREAMLIT STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV}.CRYPTO_PRICES_${STREAMLIT_ENV}
  ROOT_LOCATION = '@STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV}.CRYPTO_APP_STAGE'
  MAIN_FILE = 'app.py'
  QUERY_WAREHOUSE = STREAMLIT_WH
  TITLE = 'Crypto Daily Prices (${STREAMLIT_ENV})';

GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE CRYPTO_PIPELINE_ROLE;
GRANT USAGE ON DATABASE STREAMLIT_DB TO ROLE CRYPTO_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV} TO ROLE CRYPTO_PIPELINE_ROLE;
GRANT USAGE ON STREAMLIT STREAMLIT_DB.STREAMLIT_${STREAMLIT_ENV}.CRYPTO_PRICES_${STREAMLIT_ENV} TO ROLE CRYPTO_PIPELINE_ROLE;
